# Generated by Django 2.2.24 on 2021-10-29 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='序号')),
                ('product_name', models.CharField(max_length=50, verbose_name='商品名称')),
                ('product_price', models.DecimalField(decimal_places=3, max_digits=3, verbose_name='价格')),
                ('product_warehouse', models.CharField(max_length=50, verbose_name='模式')),
                ('product_shop_name', models.CharField(max_length=50, verbose_name='店铺名称')),
                ('product_url', models.CharField(max_length=50, verbose_name='产品链接')),
                ('product_location', models.CharField(max_length=50, verbose_name='产地')),
                ('product_function', models.CharField(max_length=50, verbose_name='功能')),
                ('product_people', models.CharField(max_length=50, verbose_name='使用人群')),
                ('product_hair', models.CharField(max_length=50, verbose_name='适用发质')),
                ('goodRate', models.DecimalField(decimal_places=3, max_digits=3, verbose_name='评分')),
                ('commentSum', models.CharField(max_length=50, verbose_name='评论数目')),
            ],
        ),
    ]
