# Generated by Django 2.2.24 on 2021-10-29 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='id',
            field=models.IntegerField(max_length=50, primary_key=True, serialize=False, verbose_name='序号'),
        ),
    ]
