# Generated by Django 2.2.24 on 2021-10-29 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_auto_20211029_1201'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='table',
            table='table',
        ),
    ]
