# Generated by Django 2.2.24 on 2021-10-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_auto_20211029_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='goodRate',
            field=models.CharField(max_length=50, verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='table',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='序号'),
        ),
        migrations.AlterField(
            model_name='table',
            name='product_price',
            field=models.CharField(max_length=50, verbose_name='价格'),
        ),
    ]
