# Generated by Django 2.2.24 on 2021-10-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0005_auto_20211029_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='序号'),
        ),
    ]
